// web-server/my-svelte-project/src/App.svelte
<script>
  let items = [];
  let newItem = "";

  function addNewItem() {
    items = [...items, newItem];
    newItem = "";
  }
</script>

<main>
  <ul>
    {#each items as item (item)}
      <li>
        <button>{item}</button>
      </li>
    {/each}
  </ul>
  <input type="text" bind:value={newItem} />
  <button on:click={addNewItem}>Add new item</button>
</main>

<style>
</style>

// web-server/my-solidjs-app/src/App.jsx
import { createSignal } from "solid-js";
import "./App.css";

function App() {
  const [items, setItems] = createSignal([]);
  let newItem;

  function addToItems() {
    let newItems = [...items(), newItem.value];
    setItems(newItems);
    newItem.value = "";
  }

  return (
    <>
    <ul>
      {items().map((item) => (
        <li>{item}</li>
      ))}
      </ul>
        <input type="text" ref={newItem}/>
        <button onClick={addToItems}>
          Add
        </button>
     
    </>
  );
}

export default App;
